### ISSUE TITLE
No additional menu with zero to jupyterhub

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/jupyterlab-hub#42]
Hello

I have successfully installed this extension in my docker image launched by jupyterhub on our Kubernetes instance, but I don't see any additional menu in jupyterlab. How can I check in live that is works?

**Comment by gsemet** [comment]
Hello
Any news? Does someone has it running with zero to jupyterhub?

**Comment by choldgraf** [comment]
hmmm - if I'm not mistaken the menu should show up. Can you share your `config.yaml` file that you're using to configure the jupyterhub?

**Comment by gsemet** [comment]
I cannot put everything:
```yaml
hub:
  cookieSecret: ...
  baseUrl: /
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: ...
  uid: 1000
  fsGid: 1000
  extraEnv:
    GITLAB_HOST: "http://our.gitlab.server"
    JUPYTER_ENABLE_LAB: 1

proxy:
  secretToken: ....
  service:
    type: ClusterIP

ingress:
  enabled: true
  host: jupyter.mycompany.com
  annotations:
    ...

singleuser:
  defaultUrl: /lab
  uid: 1000
  fsGid: 1000
  storage:
    capacity: 4Gi
    dynamic:
      storageClass: ...
  extraEnv:
    EDITOR: "vim"

auth:
  type: gitlab
  gitlab:
    clientId: ...
    clientSecret: ...
    callbackUrl: ...
  admin:
    access: true
    users:
      - ...
  state:
    enabled: true
    cryptoKey: ...

rbac:
  ...

prePuller:
  hook:
    enabled: false

cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
```

**Comment by gsemet** [comment]
Oh, I forgot to override the cmd:
```yaml
hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']
```
